### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by taoyang1122** [google-research/scenic#321]
I am trying to install scenic following the instructions (pip install .). I am using conda to create environment. Python=3.9.1, pip=21.2.4. I am getting the following information
`INFO: pip is looking at multiple versions of pandas to determine which version is compa
tible with other requirements. This could take a while.`
`INFO: This is taking longer than usual. You might need to provide the dependency resolv
er with stricter constraints to reduce runtime. If you want to abort this run, you can 
press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https
://pip.pypa.io/surveys/backtracking`
It is taking hours and still not finished. I tried different versions of python and pip but still not work. Could you please let me know how to solve this? Thanks.

**Comment by taoyang1122** [comment]
The problem is similar to this [link](https://discuss.tensorflow.org/t/object-detection-installation-dependency-problems/2983), and it is solved by doing it another time after it times out.

**Comment by Vancause** [comment]
I have the same issue. When I reinstalled the packages, the problems still occurred. It costs much more time and storage.

**Comment by MostafaDehghani** [comment]
Thanks for letting us know and sorry for the inconvenience! #332 should fix this issue. Feel free to reopen this issue if you had any other problem.
